### ISSUE TITLE
请问一下 如何 在项目中使用  

### ISSUE THREAD

**Issue by Thekingofweb** [yangjingyu/mobile-tree#1]
我尝试在 项目中 使用  npm install vue-mobile-tree  但是没法安装

**Comment by yangjingyu** [comment]
您好，能提供下详细信息么？ 我刚刚试了npm install vue-mobile-tree 没有问题的

**Comment by Thekingofweb** [comment]
现在 又可以 了 这么神奇的吗？？
![image](https://user-images.githubusercontent.com/25196954/83242842-a498c900-a1cf-11ea-9ad6-e5b071afed4b.png)，谢谢了

**Comment by Thekingofweb** [comment]
![image](https://user-images.githubusercontent.com/25196954/83243268-3e607600-a1d0-11ea-98aa-54d75b5fab80.png)

**Comment by yangjingyu** [comment]
这个报错不是项目的问题哦，应该npm上某节点还没有备份，或者缓存导致的

> 另外这个插件还在不断完善中，有啥建议可以提哦，合理的话支持可能会支持定制化开发

**Comment by Thekingofweb** [comment]
好的，刚也是无意找到这个项目 已star，用的过程中 有问题再向您请教

**Comment by Thekingofweb** [comment]
![image](https://user-images.githubusercontent.com/25196954/83245428-4c63c600-a1d3-11ea-89da-4a6572c4d30b.png)
是因为 你的版本更高欧得原因？

**Comment by yangjingyu** [comment]
update v2
