### ISSUE TITLE
手机端点击checkbox很困难

### ISSUE THREAD

**Issue by xubillde** [yangjingyu/mobile-tree#5]
1.默认设置时，点击一下，整个cell颜色变灰，checkbox边框变成蓝色。很难让checkbox变成选中状态。
2.然后更换属性后，点击整个cell让其选中，会有两处问题。点击cell能选中，但是很难点击checkbox选中；箭头展开比较难点

以上有什么解决方法吗？

补充一下
添加* { touch-action: pan-y; } 属性，chrome上调试模式的手机点击选中效果很好，但是到手机端效果还是挺差的。
使用vue+vant框架

**Comment by yangjingyu** [comment]
感谢您的反馈，我稍后会查看这个问题，您还有其他具体的信息可以提供么，例如效果截图，手机型号

**Comment by xubillde** [comment]
![image](https://user-images.githubusercontent.com/16568644/90599484-8919e900-e227-11ea-9113-402df63b073a.png)
类似就沈阳这效果。已排除是由于限制个数引起
iPhone 6sp

**Comment by yangjingyu** [comment]
已经确定问题原因么？

**Comment by xubillde** [comment]
没有

**Comment by xubillde** [comment]
你好，有思路解决吗？

**Comment by yangjingyu** [comment]
您好，目前我并未复现此问题，或者您将代码贴出来？另外是否数据量很大，并使用了virtual ？

**Comment by xubillde** [comment]
没有，我使用了另一个框架vue-treeselect。看了源码没有适配移动端。
![image](https://user-images.githubusercontent.com/16568644/90998505-d7980080-e5f6-11ea-95e9-18946264f7de.png)
我打算修改他的源码，'mousedown'外，添加一个，touchstart的逻辑来支持移动端。不知道你这边是不是类似的问题。
