### ISSUE TITLE
你好  虚拟列表和显示的不一样

### ISSUE THREAD

**Issue by onaikoto** [yangjingyu/mobile-tree#6]
这是网页显示的
![image](https://user-images.githubusercontent.com/70185769/91117516-59546080-e6c1-11ea-97cc-56dae07e6200.png)
这是把项目下下来显示的
![image](https://user-images.githubusercontent.com/70185769/91117549-7426d500-e6c1-11ea-830f-c1127069328e.png)

两个不一样  是哪有问题吗？

**Comment by yangjingyu** [comment]
面包屑，单独使用 vs-breadcrumb组件

```html

<vs-breadcrumb  class="vs-tree-breadcrumb">
    <vs-breadcrumb-item v-for="(item, index) in breadcrumbs" :key="item.id">
      <a @click="onCutCrumb(index)">{{item.data.name}}</a>
    </vs-breadcrumb-item>
 </vs-breadcrumb>

```

```js

onCutCrumb(pos = -1) {
    this.$refs.tree.onCutCrumb(pos);
 }

```

**Comment by onaikoto** [comment]
这个树组件能在vue2.5以下1.0以上使用吗？
