### ISSUE TITLE
可否添加自定义展开 收起节点的图标呢？

### ISSUE THREAD

**Issue by xiaoxian521** [yangjingyu/mobile-tree#8]
作者，你好   可否添加自定义展开 收起节点的图标呢？

**Comment by yangjingyu** [comment]
可以的，可以在组件上添加icon-class="custom-xxx", 自定义您喜欢的样式

**Comment by xiaoxian521** [comment]
这个icon-class具体是什么设置他的样式  还是可用字体图标去替换原来的图标呢？

**Comment by yangjingyu** [comment]
1. `<vs-tree icon-class="xxx"></vs-tree>`
2. 可以选择用已有字体图标去做替换

**Comment by xiaoxian521** [comment]
有展开和收起两种  这个设置 是否怎么支持两种呢？

**Comment by weiweidong1993** [comment]
> 有展开和收起两种 这个设置 是否怎么支持两种呢？

应该有专门的插槽  直接替换即可
